### ISSUE TITLE
Ballistics don't appear on the bottom of the bullets search, also where is the v1.18 release?

### ISSUE THREAD

**Issue by Zotikus1001** [hwangshkr/TarkovPriceViewer#3]
Pretty much what I said in the title.

Loving the tool tho.
Thank you :)

Also, if you want to implement the image recognition, take a look at "RatScanner" for inspiration. But the way they did it, from the middle to the top of the screen, it doesnt recognize the item images properly, because of the light glow that the inventory screen has.
I guess they are comparing every single pixel color 100% exactly. It could me mitigated by adding a lower and higher threshold to images before trying to recognize. It would make it work much better.

Image recognition would be a great option to add, since the way you have it right now, we need to wait for the item name tooltip to appear, and it takes a bit of time.

**Comment by matifanger** [comment]
> 

@Zotikus1001 I just build the v1.18 release,  but ballistics doesn't work on that version either.
Also, I think image recognition would be great, it can be very fast.

Anyways, I think @hwangshkr is not updating this project anymore.

**Comment by Zotikus1001** [comment]
> > 
> 
> @Zotikus1001 I just build the v1.18 release, but ballistics doesn't work on that version either. Also, I think image recognition would be great, it can be very fast.
> 
> Anyways, I think @hwangshkr is not updating this project anymore.

I managed to find and fix it myself. :)

**Comment by matifanger** [comment]
> 

That's great! I will test it out later.

U should do a PR to keep improving this tool and help the creator. (If he is still here)

**Comment by matifanger** [comment]
> > > 
> > 
> > 
> > @Zotikus1001 I just build the v1.18 release, but ballistics doesn't work on that version either. Also, I think image recognition would be great, it can be very fast.
> > Anyways, I think @hwangshkr is not updating this project anymore.
> 
> I managed to find and fix it myself. :)

That's great! I will test it out later.

U should do a PR to keep improving this tool and help the creator. (If he is still here)

**Comment by hwangshkr** [comment]
oh guys. Thanks to using this program, but I.... have no interest with the.... EFT now..... but really thanks!
